name: Spleef
version: '1.0-SNAPSHOT'
main: org.examplef.spleef.Spleef
api-version: '1.21'
commands:
  arena:
  areload:
  terminate:
    permission: spleef.forcestop
    permission-message: §cYou cannot use this.
softdepend: [ASPaperPlugin]